### ISSUE TITLE
Beep sound skipping

### ISSUE THREAD

**Issue by doc1011** [realA10001986/Time-Circuits-Display#10]
Hi there

Running version  A10001986 (JAN062024) with the most recent sound pack installed. the beep sounds on startup are not running consistently. When set to 30 secs, 60 secs or On, the TCD will beep a few times, skip a beep, continue beeping a few more times, skip again, etc. I've tried refreshing the firmware, reinstalling the sound pack and a different SD card. 

Other sounds are working, and music can be played, however I have just noticed that every once in a while, hitting the enter button will cause the white light to flash, but no there is no sound - it is intermittent. It is the same with the keypad presses - sometimes there is no sound. I've not noticed this previously and the only changes I have made recently is the firmware, and changing the speedo display type.

Cheers!

**Comment by realA10001986** [comment]
Can't reproduce.

Are you using the volume knob, or a fixed level? If the pot is used, this might happen if it is set to a very low volume. Since the pot is very unreliable (ie the values read vary heavily), it might be that sometimes "0" is read upon sound-start, sometimes not.

**Comment by doc1011** [comment]
Ah that may be it - I did turn it down this evening to be fair. I will turn it up and give it another go - hopefully that's all it is. Will post the outcome. 

Thanks!

**Comment by doc1011** [comment]
That was totally the issue. I turned up the volume with the pot and working perfectly again. 

Thanks you!

**Comment by realA10001986** [comment]
Thanks for the confirmation!
