### ISSUE TITLE
Audio file playback feature

### ISSUE THREAD

**Issue by gullwing12** [realA10001986/Time-Circuits-Display#13]
Updated to latest software and sound pack. Now when I hold down the #5 button to play an audio file the TCD locks up and has to be powered down. It was working prior to the update.

**Comment by gullwing12** [comment]
Yes they are mp3 format. Not sure of the bitrate. Would think though if it worked with yhe prior than it should work with the updated software.

**Comment by realA10001986** [comment]
I would think so, too. However, as said, I just tested this and it works fine here.

What version were you on before the update? How old in about?

**Comment by gullwing12** [comment]
Reloaded the mp3 files seems to have solved the issue.
