### ISSUE TITLE
Proposal of new function in Firmware

### ISSUE THREAD

**Issue by Fabiobttf** [realA10001986/Time-Circuits-Display#2]
Hi

I would ask if it possible to do some change in firmware;

How you know in my old previous mail, I have installed sensor light and temperature sensor in the TCD and they works good;

When the TCD is in night mode (low light), only the present time is ON, but  I'd like to see in the night mode also a temperature in speedometer (with different brightness)

Ii'd like to change brightness of speedometer in 3 cases:

- speedometer in time sequence (as now)
- temperature on speedometer (as now)
- night mode - temperature/speedometer (new function. now speedometer  is off in night mode )

Thanks if you want to implement this function, otherwise your work is fantastic just now;

bye

Fabio

**Comment by realA10001986** [comment]
I guess that's doable.

**Comment by Fabiobttf** [comment]
thanks a lot

**Comment by realA10001986** [comment]
Done.

**Comment by Fabiobttf** [comment]
Wow, very fast,

this evening I'll try

thanks

**Comment by Fabiobttf** [comment]
New Firmware working good, now i have temperature in speedometer also in night mode, fantastic;
the new features "beep" not working for me but I think the same problem with audio pack:
I ectract sound-pack archive and copy all to my sd card, but when I reeboot the tcd auto installation not run and in menu i can't install manually;
The only difference in my SD card and your sound-pack archive is alarm.mp3 (i used alternative sound- power of love) and add files for key3.mp3 and key6.mp3;

by the way I have built a case for speedometer and i had a strange problem, during the night the year change from 2023 to 2165;
Never happened before because without the case I had a short wire to sensor and speedometer to TCD ;with case i used about 50cm lenght wire from sensor to TCD.
I solved it with pullup resistance on SDA and SCL line;
I had 1k9ohm on SDA and 2k4ohm in SCL, 
so I soldering 20K resistor to SDA(1K9//20K=about 1k8 ohm) and 8k2 resistor in SCL(2k4//8k2=about 1k8 ohm)
For now with pullup of 1k8 ohm working good and year is stable to 2023;
I don't know if this is only my problem but maybe useful to other users with same problems (I think noise in SDA/SCL line due long wire)

**Comment by realA10001986** [comment]
The EXACT and COMPLETE contents of the sound-pack archive must be on the SD during power-up, otherwise the installer won't start. You can copy your alarm and other sounds back to the SD later, but if you want the installer to show up, all the original files must be on the SD.

"2165" means the RTC chip malfunctioned (ie it returned all 0xff when being read), I had that a couple of times as well. This might happen if there is noise on the i2c bus, so you did exactly the right thing to either pull it, or make the wire shorter. This is not a software problem.

**Comment by Fabiobttf** [comment]
Thanks a lot,


I copied all files but I don't understand to copy other sounds back to the SD later;


Now working ;)


I hope my issue in the sound and in I2C will be useful to other users;


Thanks

**Comment by realA10001986** [comment]
Step 1: Either delete all files from the SD, or move all files of the top directory into a newly created sub-directory.
Step 2: Extract the sound-pack and copy ALL files in the zip to the top directory of the SD
Step 3: Insert this SD into the TCD, power up the TCD
Step 4: Install audio files on TCD
Step 5: Power down the TCD, remove SD from TCD
Step 6: On the computer, delete the sound-pack files from the SD, and copy to the SD whatever you want (or restore its previous contents, if moved into a sub-directory in step 1)

**Comment by realA10001986** [comment]
Closing this, as the initial issue was resolved.
