### ISSUE TITLE
Suggestion - Beep "modes"

### ISSUE THREAD

**Issue by TechieNetGuy** [realA10001986/Time-Circuits-Display#3]
Would it be possible to have an "on/off/auto" setting for the beeps?  On and off would be as they are today, Auto would turn the beep on for a selectable amount of time - after an "event" - travel, after power on, after touching the keypad.

So let's say "auto" is selected, and an idle timer of 60 seconds is set.  The beeps will occur/start when the TCD is powered up, keypad entry occurs, a time travel occurs, etc.  Beeping would continue until 60 seconds after the device is "idle", and then stops.  Basically an idle timer/timeout for the beeping sound.  Idle timer could be a selection of hard coded options like the time rotation setting (15/30/60 seconds), or a user defined time.  

This might create a bunch of work because of the idle timer concept - like needing to track/reset the idle timer when keys are pressed.  Maybe limiting it to start for the pre-set amount of time only after a time travel and "power up" from Fake off and actual off.

**Comment by realA10001986** [comment]
I'll think about it, but at first glance that concept does not appear very intuitive, and users will then probably want a selectable timeout, selectable events on when to start the beep again, and so on... I don't plan on ending up in config options hell. But again, I'll think about it.
