### ISSUE TITLE
timing of time travel

### ISSUE THREAD

**Issue by Fabiobttf** [realA10001986/Time-Circuits-Display#4]
Hi,
always me :)

I made a home made flux capacitor and I connected it with IO14;
I have some problem to synchronized the TCD with my flux capacitor effect, is it possible to have the time(duration in seconds) from start (IO14 High)?:

- first time  departure time / present time/destination time blinking
- all display off first time
- display disruption
- all display off second time
- display ON

thanks if it possible

bye
Fabio

**Comment by realA10001986** [comment]
I am not sure I understand: You need to know the time it takes from
- first blink to all off
- all off to disruption
- and so on?

**Comment by realA10001986** [comment]
Assuming you meant what I think you meant, there are several phases:

- phase 1 starts with IO14 going HIGH, and takes 5000ms
- phase 2 is 2800ms while the displays blink as a whole,
- phase 3 is 1600ms while the displays are all off,
- phase 4 is 1000ms while the display show random stuff part 1,
- phase 5 is 1200ms while the display show random stuff part 2.

At the end of phase 5, IO14 goes LOW. The displays go on 1500ms after the end of phase 5.

(I hope this is all correct, it's from the top of my head)

**Comment by Fabiobttf** [comment]
Yes this is what I need,

I think just add the time or is there some pause between different phase ?

example:

* phase 1 starts with IO14 going HIGH, and takes.................... 5000ms
* phase 2 is 2800ms while the displays blink as a whole,......... (5000+2800)
* phase 3 is 1600ms while the displays are all off,......................(7800+1600)
* phase 4 is 1000ms while the display show random stuff part 1,(9400+1000)
* phase 5 is 1200ms while the display show random stuff part 2.(10400+1200)
thanks a lot

bye

**Comment by realA10001986** [comment]
But don't expect the timing to always be exact, depending on the current work load (GPS, WiFi, etc) it might vary slightly.

**Comment by Fabiobttf** [comment]
ok, I'll try with this time,

I have no wifi or GPS  connection

only have temperature sensor, speedometer  and light sensor, but I think this sensor not enable during time travel sequence (except speedometer);

**Comment by alalal80** [comment]
Good evening,
I have several ideas to increase this fabulous machine, for the alarm,
why not add an output that will control a servo motor to ring the ticks of the clock instead of the sound of the clock.
still great work.
have the possibility of having a countdown for a given date and time.
Well, thank you again for your work.
