### ISSUE TITLE
News functions

### ISSUE THREAD

**Issue by alalal80** [realA10001986/Time-Circuits-Display#5]
Good evening,
here is a small list of request for evolutions:
 - have the possibility of programming a countdown but with a programmed day-Month-year and hour-minutes.
- Is it possible to have an output for the programmed alarm and have the choice between the sound or the active output.
Thank you for your work.

**Comment by alalal80** [comment]
Good evening,
thank you for your reply.
can we not limit the time counter to 1 year, this will limit the calculations.
Too bad for the outings, the goal was to operate a motor.
What are the future functionalities that you will program?
Cordially.

**Comment by realA10001986** [comment]
What is your goal with this timer? Displaying a countdown (briefly, after entering a code), or having an alarm/reminder?
