### ISSUE TITLE
Beep Mode 2 and 3 (auto) - not working after time travel.

### ISSUE THREAD

**Issue by TechieNetGuy** [realA10001986/Time-Circuits-Display#7]
At some point recently AUTO beep mode stopped working after time travel.

If beep auto beep mode 2 or 3 is active, the beeps are muted after time travel - the 30 or 60 second mute delay is not honored.  If a return from time travel (push and hold 9) is activated the beeps and time delay mute do work as expected.  

The beeps appear to work as expected in all other unmuting situations (fake power, reboot, enter of new date, etc).

**Comment by realA10001986** [comment]
Ah, got it. Will be fixed shortly.
