### ISSUE TITLE
Suggestions / Enhancements 

### ISSUE THREAD

**Issue by TechieNetGuy** [realA10001986/Time-Circuits-Display#9]
On the TCD:
As long as I can remember, this has been the case in Night Mode.  The ” : “between the hour and min display is “OFF” when in Night Mode.  During normal operation these flash once per second.  I can understand not having the flashing during Night Mode, but would it be possible to have the lights remain ON without blink during Night Mode?  This would make it easier to at a glance identify the hour and min digits when it is dark (and you are half awake if using this as a clock).

On the TCD and Flux Capacitor:
Press and hold #9 is back to “real time”.  Not sure if the intent of this was to “time travel” back like a standard travel event, or to just bring the TCD back to “default”. Currently it runs a shorter time travel sequence compared to when you press and hold 0 for a traditional time travel sequence.  Additionally it DOES reset the beep timer for the 30/60 second duration upon finishing the cycle.  However it DOES NOT trigger activation of the Flux Capacitor (over BTTFN).  So with the shortened sequence and now lack of Flux interaction - to me if this is more of a “soft reset” back to “real time”. I would suggest it be made to either (fixed or optionally) respond like a “normal” time travel OR with similar visuals and sound that occur when hitting enter after entering a new destination date (no actual travel sequence, just display reset - with or without Auto Beep reset?!).  Bottom line it just seems like press and hold 9 is and has been operating in strange way (somewhere between a full time travel and soft reset of the current time), which is even more unusual now with the addition of the Flux Capacitor and lack of interaction with the Flux Capacitor. For me no travel event, and no Flux interaction is fine - soft reset get me back "home", but that is just me.  Right now it is in a strange form somewhere in the middle and I think it should be solidified as a full travel, or just a display reset.  

On the TCD and Flux Capacitor:
I like the way that the Beep Auto mode works. I also like the Wakeup/Sleep mode interaction between the TCD and the Flux (Night Mode, push and hold 4 for wake and sleep), etc.  However I think that the TCD should also “wake up” the display and/or sounds on the Flux Capacitor when a new date is entered on the TCD keypad (which currently restarts the BEEP when in Auto mode). When Auto Beep is idle, the TCD beeps are silent, and the Flux Sounds and/or Display are likely idle/off as well.  Currently when you enter a new destination date on the TCD and hit enter, the beeps start on the TCD, but the Flux sits domant (until time travel starts). I think it would be nice to see the visual and audio of the Flux follow the TCD beep behaviors - and wake up the sounds and display functions of the Flux Capacitor. The Flux has Screen Saver and Sound Mode, maybe sound mode settings can supersede Screen Saver when tied to a TCD?  Not sure, but it would be nice to keep the option of having visuals stay active with or without sound and have influence from the TCD that matches Beep Mode of the TCD.  Bottom line it would be nice to have the Flux wake up prior to the start of the time travel sequence.  Maybe an option to tie or separate display and sound timers on the Flux, and then a simple "wake-up/sleep" signal when beeps @ 30/60 are engaged and disengaged - keeps the stand alone flexibility and enables sound and/or visual when the TCD beeps are activated.

**Comment by realA10001986** [comment]
Hm, sounds all reasonable. Are you running the firmware from my repo or from CircuitSetup? If from mine, you can try this out and tell me your opinion:

https://www.dropbox.com/scl/fi/foh2wuew45ik3d9pxckgz/timecircuits-A10001986.ino.nodemcu-32s.bin?rlkey=68nltgeazmmms95p7nieigul2&dl=0

(No changes needed on FC side; I don't have access to my FC ATM, so untested as regards synchronization).

**Comment by TechieNetGuy** [comment]
I am running your firmware....

**Comment by realA10001986** [comment]
Allright then,
- colons on in nm
- wakeup sent to network clients when entering date/time
- wakeup sent to network clients upon "return from time travel"; I don't want to make it a full time travel since it was indeed meant as a kind of display reset, but downgrading it to just a display reset without further ado I don't find appealing either.

**Comment by realA10001986** [comment]
If that q&d "fix" works, I'll do it properly, which also requires changes on the FC side.

**Comment by TechieNetGuy** [comment]
The code you linked to above did not show any change in function for the FC "wakeup".

**Comment by realA10001986** [comment]
Huh?! That's odd. Can't test myself, am at work, but here are new versions for TCD and FC, with a real "wakeup" mechanism (at least in theory) rather than abusing the prepare function:

https://www.dropbox.com/scl/fi/foh2wuew45ik3d9pxckgz/timecircuits-A10001986.ino.nodemcu-32s.bin?rlkey=68nltgeazmmms95p7nieigul2&dl=0
https://www.dropbox.com/scl/fi/xiq98yh3xabw95pivssck/fluxcapacitor-A10001986.ino.nodemcu-32s.bin?rlkey=70er6n9ncgeqtcd5fz7cc54th&dl=0

**Comment by realA10001986** [comment]
The FC should wake up
- when holding '9',
- when pressing ENTER after typing a destination date

**Comment by TechieNetGuy** [comment]
With those 2 files, yes upon new date/time [enter] and push and hold 9 - wakeup of FC appears to be working

**Comment by TechieNetGuy** [comment]
Just noticed this on push and hold 4....

On the TCD, if beeps have not expired and you push and hold 4 it goes NM and silent, if you push and hold 4 again to come out of NM, the beeps restore IF there was/is still time on the beep timer.  However, the FC comes back with just lights, no sound - even if there was till time on the timeout timer for sound.  Probably not a huge deal in the big picture, because this is all within the 30/60 timeout for beep and screen save - but consistency might be desired just for future head scratching elimination.  

Coming out of NM with push and hold 4 with an expired beep timer seems to be fine, TCD stays silent, and the FC just comes out of Screen Save.  

So the sound timer on the FC is being auto expired when entering NM and that doesn't seem to be how it is handled for the TCD beep/sound timer.

**Comment by realA10001986** [comment]
Ok, good catch again, the TCD now auto-expires.

https://www.dropbox.com/scl/fi/foh2wuew45ik3d9pxckgz/timecircuits-A10001986.ino.nodemcu-32s.bin?rlkey=68nltgeazmmms95p7nieigul2&dl=0

**Comment by TechieNetGuy** [comment]
Everything seems to be working as expected, thanks for these enhancements!
